#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
packages:
  - nginx
  - java-11-openjdk
  - sqlcl
runcmd:
  - systemctl enable nginx
  - systemctl start nginx
  - firewall-offline-cmd --add-port=80/tcp
  - systemctl reboot
